name: backstage-validator
permissions:
  contents: read

on:
  push:
    branches-ignore:
      - "main"

jobs:
  backstage-entity-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: RoadieHQ/backstage-entity-validator@v0.5.0
        with:
          path: 'catalog-info*.yaml'
