name: Changesets

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      label:
        description: "Pick a label/description for the prerelease. The version will be 0.0.0-{label}-{timestamp}. It doesn't have to be unique, but it has to contain at least one letter, is lowercase. Only dots and dashes are valid, no underscores."
        required: true
        type: string
  push:
    branches:
      - main

jobs:
  trigger:
    uses: ./.github/workflows/kotlin-changesets.yaml@0c74aca9f30f45a3746885a7125033318f90a1f7
    with:
      label: ${{ github.event.inputs.label }}
    secrets: inherit