name: CI
permissions:
  contents: read

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build, test, lint
        run: |
          ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

  snyk-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts
          path: build/libs

      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions/gradle-jdk17@master
        continue-on-error: true
        with:
          args: --all-projects --severity-threshold=high
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_ACTION_TOKEN }}
